name: Fly Arrow Fly
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70268
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0
  lightness: 0.42557940329425037
  saturation: 0.6553998060990125
  rhythmicContrast: 0.16077156946994364
purpose: []
